<?php

include_once('redbull_base.features.inc');

function redbull_base_theme() {
  return array(
    'ting_related_materials' => array(
      'arguments' => array('collection' => NULL),
      'template' => 'ting_related_materials'
    ),
  );
}

/**
 * Implementation of hook_imagecache_default_presets_alter().
 */
function redbull_base_imagecache_default_presets_alter(&$presets) {
  if (!empty($presets['ting_search_carousel'])) {
    $presets['ting_search_carousel']['actions'][0]['actions'] = 'imagecache_scale_and_crop';
    $presets['ting_search_carousel']['actions'][0]['data']['width'] = '100';
    $presets['ting_search_carousel']['actions'][0]['data']['height'] = '160';

    $presets['ting_search_carousel']['actions'][1]['data']['exact']['width'] = '100';
    $presets['ting_search_carousel']['actions'][1]['data']['exact']['height'] = '160';
  }
}