<?php

include_once('redbull_base.features.inc');

function redbull_base_theme() {
  return array(
    'ting_related_materials' => array(
      'arguments' => array('collection' => NULL),
      'template' => 'ting_related_materials'
    ),
  );
}

/**
 * Implementation of hook_imagecache_default_presets_alter().
 */
function redbull_base_imagecache_default_presets_alter(&$presets) {
  if (!empty($presets['ting_search_carousel'])) {
    $presets['ting_search_carousel']['actions'][0]['actions'] = 'imagecache_scale_and_crop';
    $presets['ting_search_carousel']['actions'][0]['data']['width'] = '100';
    $presets['ting_search_carousel']['actions'][0]['data']['height'] = '160';

    $presets['ting_search_carousel']['actions'][1]['data']['exact']['width'] = '100';
    $presets['ting_search_carousel']['actions'][1]['data']['exact']['height'] = '160';
  }
}

/**
 * Implementation of hook_rules_defaults().
 */
function redbull_base_rules_defaults() {
  return array(
    'rules' => array(
      'rules_redbull_article_node_insert' => array(
        '#type' => 'rule',
        '#set' => 'event_node_insert',
        '#label' => 'redbull_article_saved',
        '#active' => 1,
        '#weight' => '0',
        '#categories' => array(
          '0' => 'Content',
          'redbull_base' => 'redbull_base',
        ),
        '#status' => 'default',
        '#conditions' => array(
          '0' => array(
            '#weight' => 0,
            '#type' => 'condition',
            '#settings' => array(
              'type' => array(
                'article' => 'article',
              ),
              '#argument map' => array(
                'node' => 'node',
              ),
            ),
            '#name' => 'rules_condition_content_is_type',
            '#info' => array(
              'label' => 'Created content is article',
              'label callback' => FALSE,
              'arguments' => array(
                'node' => array(
                  'type' => 'node',
                  'label' => 'Content',
                ),
              ),
              'module' => 'Node',
            ),
          ),
        ),
        '#actions' => array(
          '0' => array(
            '#info' => array(
              'label' => 'Clear the cache of a redbull_article_list view.',
              'label callback' => FALSE,
              'arguments' => array(
                'view' => array(
                  'type' => 'string',
                  'label' => 'View',
                  'description' => 'Specify the view you want to clear.',
                ),
              ),
              'module' => 'Cache Actions',
            ),
            '#name' => 'cache_actions_action_clear_views_cache',
            '#settings' => array(
              'view' => 'redbull_article_list',
            ),
            '#type' => 'action',
            '#weight' => 0,
          ),
          '1' => array(
            '#weight' => 0,
            '#info' => array(
              'label' => 'Clear the cache of a redbull_inspiration_list view.',
              'label callback' => FALSE,
              'arguments' => array(
                'view' => array(
                  'type' => 'string',
                  'label' => 'View',
                  'description' => 'Specify the view you want to clear.',
                ),
              ),
              'module' => 'Cache Actions',
            ),
            '#name' => 'cache_actions_action_clear_views_cache',
            '#settings' => array(
              'view' => 'redbull_inspiration_list',
            ),
            '#type' => 'action',
          ),
          '2' => array(
            '#weight' => 0,
            '#info' => array(
              'label' => 'Clear the cache of a roedovre_blog_inspiration view.',
              'label callback' => FALSE,
              'arguments' => array(
                'view' => array(
                  'type' => 'string',
                  'label' => 'View',
                  'description' => 'Specify the view you want to clear.',
                ),
              ),
              'module' => 'Cache Actions',
            ),
            '#name' => 'cache_actions_action_clear_views_cache',
            '#settings' => array(
              'view' => 'roedovre_blog_inspiration',
            ),
            '#type' => 'action',
          ),
          '3' => array(
            '#weight' => 0,
            '#info' => array(
              'label' => 'Clear the cache of a roedovre_taxonomy_term_view view.',
              'label callback' => FALSE,
              'arguments' => array(
                'view' => array(
                  'type' => 'string',
                  'label' => 'View',
                  'description' => 'Specify the view you want to clear.',
                ),
              ),
              'module' => 'Cache Actions',
            ),
            '#name' => 'cache_actions_action_clear_views_cache',
            '#settings' => array(
              'view' => 'roedovre_taxonomy_term_view',
            ),
            '#type' => 'action',
          ),
        ),
        '#version' => 6003,
      ),
      'rules_redbull_article_node_update' => array(
        '#type' => 'rule',
        '#set' => 'event_node_update',
        '#label' => 'redbull_article_updated',
        '#active' => 1,
        '#weight' => '0',
        '#categories' => array(
          '0' => 'Content',
          'redbull_base' => 'redbull_base',
        ),
        '#status' => 'default',
        '#conditions' => array(
          '0' => array(
            '#type' => 'condition',
            '#settings' => array(
              'type' => array(
                'article' => 'article',
              ),
              '#argument map' => array(
                'node' => 'node',
              ),
            ),
            '#name' => 'rules_condition_content_is_type',
            '#info' => array(
              'label' => 'Updated content is article',
              'arguments' => array(
                'node' => array(
                  'type' => 'node',
                  'label' => 'Content',
                ),
              ),
              'module' => 'Node',
            ),
            '#weight' => 0,
          ),
        ),
        '#actions' => array(
          '0' => array(
            '#info' => array(
              'label' => 'Clear the cache of a redbull_article_list view.',
              'label callback' => FALSE,
              'arguments' => array(
                'view' => array(
                  'type' => 'string',
                  'label' => 'View',
                  'description' => 'Specify the view you want to clear.',
                ),
              ),
              'module' => 'Cache Actions',
            ),
            '#name' => 'cache_actions_action_clear_views_cache',
            '#settings' => array(
              'view' => 'redbull_article_list',
            ),
            '#type' => 'action',
            '#weight' => 0,
          ),
          '1' => array(
            '#weight' => 0,
            '#info' => array(
              'label' => 'Clear the cache of a redbull_inspiration_list view.',
              'label callback' => FALSE,
              'arguments' => array(
                'view' => array(
                  'type' => 'string',
                  'label' => 'View',
                  'description' => 'Specify the view you want to clear.',
                ),
              ),
              'module' => 'Cache Actions',
            ),
            '#name' => 'cache_actions_action_clear_views_cache',
            '#settings' => array(
              'view' => 'redbull_inspiration_list',
            ),
            '#type' => 'action',
          ),
          '2' => array(
            '#weight' => 0,
            '#info' => array(
              'label' => 'Clear the cache of a roedovre_blog_inspiration view.',
              'label callback' => FALSE,
              'arguments' => array(
                'view' => array(
                  'type' => 'string',
                  'label' => 'View',
                  'description' => 'Specify the view you want to clear.',
                ),
              ),
              'module' => 'Cache Actions',
            ),
            '#name' => 'cache_actions_action_clear_views_cache',
            '#settings' => array(
              'view' => 'roedovre_blog_inspiration',
            ),
            '#type' => 'action',
          ),
          '3' => array(
            '#weight' => 0,
            '#info' => array(
              'label' => 'Clear the cache of a roedovre_taxonomy_term_view view.',
              'label callback' => FALSE,
              'arguments' => array(
                'view' => array(
                  'type' => 'string',
                  'label' => 'View',
                  'description' => 'Specify the view you want to clear.',
                ),
              ),
              'module' => 'Cache Actions',
            ),
            '#name' => 'cache_actions_action_clear_views_cache',
            '#settings' => array(
              'view' => 'roedovre_taxonomy_term_view',
            ),
            '#type' => 'action',
          ),
        ),
        '#version' => 6003,
      ),
      'rules_redbull_article_node_delete' => array(
        '#type' => 'rule',
        '#set' => 'event_node_delete',
        '#label' => 'redbull_article_deleted',
        '#active' => 1,
        '#weight' => '0',
        '#categories' => array(
          '0' => 'Content',
          'redbull_base' => 'redbull_base',
        ),
        '#status' => 'default',
        '#conditions' => array(
          '0' => array(
            '#weight' => 0,
            '#info' => array(
              'label' => 'Deleted content is article',
              'arguments' => array(
                'node' => array(
                  'type' => 'node',
                  'label' => 'Content',
                ),
              ),
              'module' => 'Node',
            ),
            '#name' => 'rules_condition_content_is_type',
            '#settings' => array(
              'type' => array(
                'article' => 'article',
              ),
              '#argument map' => array(
                'node' => 'node',
              ),
            ),
            '#type' => 'condition',
          ),
        ),
        '#actions' => array(
          '0' => array(
            '#info' => array(
              'label' => 'Clear the cache of a redbull_article_list view.',
              'label callback' => FALSE,
              'arguments' => array(
                'view' => array(
                  'type' => 'string',
                  'label' => 'View',
                  'description' => 'Specify the view you want to clear.',
                ),
              ),
              'module' => 'Cache Actions',
            ),
            '#name' => 'cache_actions_action_clear_views_cache',
            '#settings' => array(
              'view' => 'redbull_article_list',
            ),
            '#type' => 'action',
            '#weight' => 0,
          ),
          '1' => array(
            '#weight' => 0,
            '#info' => array(
              'label' => 'Clear the cache of a redbull_inspiration_list view.',
              'label callback' => FALSE,
              'arguments' => array(
                'view' => array(
                  'type' => 'string',
                  'label' => 'View',
                  'description' => 'Specify the view you want to clear.',
                ),
              ),
              'module' => 'Cache Actions',
            ),
            '#name' => 'cache_actions_action_clear_views_cache',
            '#settings' => array(
              'view' => 'redbull_inspiration_list',
            ),
            '#type' => 'action',
          ),
          '2' => array(
            '#weight' => 0,
            '#info' => array(
              'label' => 'Clear the cache of a roedovre_blog_inspiration view.',
              'label callback' => FALSE,
              'arguments' => array(
                'view' => array(
                  'type' => 'string',
                  'label' => 'View',
                  'description' => 'Specify the view you want to clear.',
                ),
              ),
              'module' => 'Cache Actions',
            ),
            '#name' => 'cache_actions_action_clear_views_cache',
            '#settings' => array(
              'view' => 'roedovre_blog_inspiration',
            ),
            '#type' => 'action',
          ),
          '3' => array(
            '#weight' => 0,
            '#info' => array(
              'label' => 'Clear the cache of a roedovre_taxonomy_term_view view.',
              'label callback' => FALSE,
              'arguments' => array(
                'view' => array(
                  'type' => 'string',
                  'label' => 'View',
                  'description' => 'Specify the view you want to clear.',
                ),
              ),
              'module' => 'Cache Actions',
            ),
            '#name' => 'cache_actions_action_clear_views_cache',
            '#settings' => array(
              'view' => 'roedovre_taxonomy_term_view',
            ),
            '#type' => 'action',
          ),
        ),
        '#version' => 6003,
      ),
      'rules_redbull_event_node_insert' => array(
        '#type' => 'rule',
        '#set' => 'event_node_insert',
        '#label' => 'redbull_event_saved',
        '#active' => 1,
        '#weight' => '0',
        '#categories' => array(
          '0' => 'Content',
          'redbull_base' => 'redbull_base',
        ),
        '#status' => 'default',
        '#conditions' => array(
          '0' => array(
            '#weight' => 0,
            '#type' => 'condition',
            '#settings' => array(
              'type' => array(
                'event' => 'event',
              ),
              '#argument map' => array(
                'node' => 'node',
              ),
            ),
            '#name' => 'rules_condition_content_is_type',
            '#info' => array(
              'label' => 'Created content is event',
              'label callback' => FALSE,
              'arguments' => array(
                'node' => array(
                  'type' => 'node',
                  'label' => 'Content',
                ),
              ),
              'module' => 'Node',
            ),
          ),
        ),
        '#actions' => array(
          '0' => array(
            '#info' => array(
              'label' => 'Clear the cache of a roedovre_event_list view.',
              'label callback' => FALSE,
              'arguments' => array(
                'view' => array(
                  'type' => 'string',
                  'label' => 'View',
                  'description' => 'Specify the view you want to clear.',
                ),
              ),
              'module' => 'Cache Actions',
            ),
            '#name' => 'cache_actions_action_clear_views_cache',
            '#settings' => array(
              'view' => 'roedovre_event_list',
            ),
            '#type' => 'action',
            '#weight' => 0,
          ),
          '1' => array(
            '#weight' => 0,
            '#info' => array(
              'label' => 'Clear the cache of a roedovre_blog_inspiration view.',
              'label callback' => FALSE,
              'arguments' => array(
                'view' => array(
                  'type' => 'string',
                  'label' => 'View',
                  'description' => 'Specify the view you want to clear.',
                ),
              ),
              'module' => 'Cache Actions',
            ),
            '#name' => 'cache_actions_action_clear_views_cache',
            '#settings' => array(
              'view' => 'roedovre_blog_inspiration',
            ),
            '#type' => 'action',
          ),
          '2' => array(
            '#weight' => 0,
            '#info' => array(
              'label' => 'Clear the cache of a roedovre_taxonomy_term_view view.',
              'label callback' => FALSE,
              'arguments' => array(
                'view' => array(
                  'type' => 'string',
                  'label' => 'View',
                  'description' => 'Specify the view you want to clear.',
                ),
              ),
              'module' => 'Cache Actions',
            ),
            '#name' => 'cache_actions_action_clear_views_cache',
            '#settings' => array(
              'view' => 'roedovre_taxonomy_term_view',
            ),
            '#type' => 'action',
          ),
        ),
        '#version' => 6003,
      ),
      'rules_redbull_event_node_update' => array(
        '#type' => 'rule',
        '#set' => 'event_node_update',
        '#label' => 'redbull_event_updated',
        '#active' => 1,
        '#weight' => '0',
        '#categories' => array(
          '0' => 'Content',
          'redbull_base' => 'redbull_base',
        ),
        '#status' => 'default',
        '#conditions' => array(
          '0' => array(
            '#type' => 'condition',
            '#settings' => array(
              'type' => array(
                'event' => 'event',
              ),
              '#argument map' => array(
                'node' => 'node',
              ),
            ),
            '#name' => 'rules_condition_content_is_type',
            '#info' => array(
              'label' => 'Updated content is event',
              'arguments' => array(
                'node' => array(
                  'type' => 'node',
                  'label' => 'Content',
                ),
              ),
              'module' => 'Node',
            ),
            '#weight' => 0,
          ),
        ),
        '#actions' => array(
          '0' => array(
            '#info' => array(
              'label' => 'Clear the cache of a roedovre_event_list view.',
              'label callback' => FALSE,
              'arguments' => array(
                'view' => array(
                  'type' => 'string',
                  'label' => 'View',
                  'description' => 'Specify the view you want to clear.',
                ),
              ),
              'module' => 'Cache Actions',
            ),
            '#name' => 'cache_actions_action_clear_views_cache',
            '#settings' => array(
              'view' => 'roedovre_event_list',
            ),
            '#type' => 'action',
            '#weight' => 0,
          ),
          '1' => array(
            '#weight' => 0,
            '#info' => array(
              'label' => 'Clear the cache of a roedovre_blog_inspiration view.',
              'label callback' => FALSE,
              'arguments' => array(
                'view' => array(
                  'type' => 'string',
                  'label' => 'View',
                  'description' => 'Specify the view you want to clear.',
                ),
              ),
              'module' => 'Cache Actions',
            ),
            '#name' => 'cache_actions_action_clear_views_cache',
            '#settings' => array(
              'view' => 'roedovre_blog_inspiration',
            ),
            '#type' => 'action',
          ),
          '2' => array(
            '#weight' => 0,
            '#info' => array(
              'label' => 'Clear the cache of a roedovre_taxonomy_term_view view.',
              'label callback' => FALSE,
              'arguments' => array(
                'view' => array(
                  'type' => 'string',
                  'label' => 'View',
                  'description' => 'Specify the view you want to clear.',
                ),
              ),
              'module' => 'Cache Actions',
            ),
            '#name' => 'cache_actions_action_clear_views_cache',
            '#settings' => array(
              'view' => 'roedovre_taxonomy_term_view',
            ),
            '#type' => 'action',
          ),
        ),
        '#version' => 6003,
      ),
      'rules_redbull_event_node_delete' => array(
        '#type' => 'rule',
        '#set' => 'event_node_delete',
        '#label' => 'redbull_event_deleted',
        '#active' => 1,
        '#weight' => '0',
        '#categories' => array(
          '0' => 'Content',
          'redbull_base' => 'redbull_base',
        ),
        '#status' => 'default',
        '#conditions' => array(
          '0' => array(
            '#weight' => 0,
            '#info' => array(
              'label' => 'Deleted content is event',
              'arguments' => array(
                'node' => array(
                  'type' => 'node',
                  'label' => 'Content',
                ),
              ),
              'module' => 'Node',
            ),
            '#name' => 'rules_condition_content_is_type',
            '#settings' => array(
              'type' => array(
                'event' => 'event',
              ),
              '#argument map' => array(
                'node' => 'node',
              ),
            ),
            '#type' => 'condition',
          ),
        ),
        '#actions' => array(
          '0' => array(
            '#info' => array(
              'label' => 'Clear the cache of a roedovre_event_list view.',
              'label callback' => FALSE,
              'arguments' => array(
                'view' => array(
                  'type' => 'string',
                  'label' => 'View',
                  'description' => 'Specify the view you want to clear.',
                ),
              ),
              'module' => 'Cache Actions',
            ),
            '#name' => 'cache_actions_action_clear_views_cache',
            '#settings' => array(
              'view' => 'roedovre_event_list',
            ),
            '#type' => 'action',
            '#weight' => 0,
          ),
          '1' => array(
            '#weight' => 0,
            '#info' => array(
              'label' => 'Clear the cache of a roedovre_blog_inspiration view.',
              'label callback' => FALSE,
              'arguments' => array(
                'view' => array(
                  'type' => 'string',
                  'label' => 'View',
                  'description' => 'Specify the view you want to clear.',
                ),
              ),
              'module' => 'Cache Actions',
            ),
            '#name' => 'cache_actions_action_clear_views_cache',
            '#settings' => array(
              'view' => 'roedovre_blog_inspiration',
            ),
            '#type' => 'action',
          ),
          '2' => array(
            '#weight' => 0,
            '#info' => array(
              'label' => 'Clear the cache of a roedovre_taxonomy_term_view view.',
              'label callback' => FALSE,
              'arguments' => array(
                'view' => array(
                  'type' => 'string',
                  'label' => 'View',
                  'description' => 'Specify the view you want to clear.',
                ),
              ),
              'module' => 'Cache Actions',
            ),
            '#name' => 'cache_actions_action_clear_views_cache',
            '#settings' => array(
              'view' => 'roedovre_taxonomy_term_view',
            ),
            '#type' => 'action',
          ),
        ),
        '#version' => 6003,
      ),
    ),
  );
}

/**
 * Implementation of hook_preprocess_ting_object().
 *
 * Rearranges object details.
 */
function redbull_base_preprocess_ting_object(&$vars) {
  /*
    type: bog
    sprog: dansk
    emneord: øl, hånd
    opstilling
    beskrivelse: indhold: ølsma
    isbn:
    version: 2udga
    omfang: 240
    udgiver: kbh. polit
  */
  // These are the ones we want first;
  $primary = array_flip(array(
    t('Type'),
    t('Language'),
    t('Subjects'),
    t('Classiciation'),
    t('Description'),
    t('ISBN'),
    t('Edition'),
    t('Publisher'),
    t('Extent'),
  ));

  $ting_details = $vars['ting_details'];
  // Collect listing of all.
  $all_items = array_merge($ting_details[0]['data'], $ting_details[1]['data'], $ting_details[2]['data']);

  // Filter out the primary for the first.
  // Create an array where the keys are in the primary order.
  $order = array_intersect_key($primary, $all_items);
  // And another one where the key has the right value (order is from
  // $all_items)
  $common = array_intersect_key($all_items, $order);
  // array_merge uses the order of the first, but last value.
  $ting_details[0]['data'] = array_merge($order, $common);
  // And add the rest to the second.
   $ting_details[1]['data'] = array_diff_key($all_items, $primary); 
  // Delete the third group.
  unset($ting_details[2]);

  $vars['ting_details'] = $ting_details;
}
